# Variables for manipulating this module.

variable "vpc_id" {
  description = "ID of the VPC in which to run Vault."
}

variable "aws_region" {
  description = "AWS Region in which to run Vault"
}

variable "resource_name_prefix" {
  description = "Prefix for created EC2 Instances.  Used for identification and Vault Node auto-join."
}

variable "private_subnet_tags" {
  description = "Tag applied to private subnets.  Used for Vault Node placement.  Nodes will only be placed into private subnets."
}

variable "allowed_inbound_cidrs_lb" {
  description = "CIDR block allowed to connect to the Vault Load Balancer.  All Clients, including the Vault Nodes themselves must be explicitly allowed."
  type        = list(string)
  default     = []
}

variable "allowed_inbound_cidrs_ssh" {
  description = "CIDR block allowed to ssh into Vault Instances.  "
  type        = list(string)
  default     = []
}

variable "vault_lb_hostname" {
  description = "DNS name for Vault Load Balancer.  If left null, the auto generated AWS LB DNS name will be used."
  default     = null
}

variable "internal_lb" {
  description = "Flag to control whether a created Load Balancer is Internal or External.  Defaults to 'true'."
  default     = true
}

variable "custom_userdata_path" {
  description = "path to custom userdata path.  If not set, module defaults to internal userdata template."
  default     = null
}

variable "common_tags" {
  description = "Map of additional tags to place on created resources."
  type        = map(string)
  default     = {}
}

variable "lb_type" {
  description = "Load balancer type.  One of 'application' or 'network'.  Defaults to 'application'."
  default     = "application"
}

variable "vault_ami_id" {
  description = "AMI ID to use for Vault nodes.  Defaults to Ubuntu 22.04, and auto detects the latest released version in your AZ."
  default     = null
}

variable "instance_type" {
  description = "EC2 instance type to use for Vault Nodes.  Defaults to 'm5.xlarge'."
  default     = "m5.xlarge"
}

variable "ssh_key_name" {
  description = "SSH Key to place on EC2 instances.  Defaults to null (No SSH Key)."
  default     = null
}

variable "vault_node_count" {
  description = "Number of Vault nodes to run.  Defaults to 5."
  default     = 5
}

variable "vault_role_name" {
  description = "Vault Role Name.  "
  default     = null
}

variable "kms_key_arn" {
  description = "ARN of an existing KMS key for Vault to use.  If not specified, we'll create one."
  default     = null
}

variable "secrets_manager_arn" {
  description = "ARN of SecretsManager secret for TLS material storage.  Autogenerated if left null."
  default     = null
}

variable "vault_version" {
  description = "Vault Version.  Defaults to '1.8.2'."
  default     = "1.8.2"
}

variable "kms_deletion_window_days" {
  description = "KMS Key deletion window.  Defaults to 7 days."
  default     = 7
}

variable "ssl_policy" {
  description = "TLS Policy on LB Listener.  Default 'ELBSecurityPolicy-TLS-1-2-2017-01'."
  default     = "ELBSecurityPolicy-TLS-1-2-2017-01"
}

variable "vault_healthcheck_path" {
  description = "Vault healthcheck path.  Default: '/v1/sys/health?activecode=200&standbycode=200&sealedcode=200&uninitcode=200'."
  default     = "/v1/sys/health?activecode=200&standbycode=200&sealedcode=200&uninitcode=200"
}

variable "vault_lb_certificate_arn" {
  description = "ARN of Certificate to use on LB TLS Listener."
  default     = null
}